default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Ensure bundler gems if using Gemfile
    # cocoapods
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: "ExportOptions.plist",
      workspace: "Runner.xcworkspace"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

